// The module for the App Wallet
const mongoose = require("mongoose");

const appWalletSchema = mongoose.Schema({
	amount: {
		type: Number,
		default: "0.00"
	},
	// this is what users would use to receice in their wallet. Its like account no. So we do not have to use the id it would be autogenerated
	walletSignature: {
		type: String,
		default: Math.floor(Math.random() * 9999)
	},
	owner: {
		type: mongoose.Schema.Types.ObjectId,
		ref: "User"
	},
	
	// Things needed for all appWallet Schema
}, { timestamps: true });

module.exports = new mongoose.model("AppWallet", appWalletSchema);